---
coverage_criteria:
  process_abort: true
fail_fast: true
includes:
- lib
integration:
  name: minitest
matcher:
  subjects:
  - MLB*
mutation:
  operators: full
  timeout: 10.0
requires:
- mlb
usage: opensource
